### ISSUE TITLE
testing convergence?

### ISSUE THREAD

**Issue by dineshmdh** [zygmuntz/spearmint#1]
Not really an issue, but I was wondering how you test for convergence (or introduce maximum number of iterations) to stop the optimization with spearmint -- here or in your "madelon" project. (And I know you had worked on this a while back, but hopefully, you will be able to help without much digging. The spearmint page recommends a user-end closing of the script, which is not really ideal..)

Thanks.

**Comment by zygmuntz** [comment]
That's a good question. I don't know a good answer. Computational budget maybe? More is not necessarily better because it might lead to overfitting.
